# Generated by Django 3.0.8 on 2020-07-06 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudemo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskdata',
            name='cost',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taskdata',
            name='name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taskdata',
            name='option_hours',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taskdata',
            name='options',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taskdata',
            name='shoping_site_content',
            field=models.CharField(blank=True, choices=[('yes', 'YES'), ('no', 'NO')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='taskdata',
            name='tech_talk',
            field=models.CharField(blank=True, choices=[('yes', 'YES'), ('no', 'NO')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='taskdata',
            name='type',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taskdata',
            name='weight',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
