# Generated by Django 3.0.8 on 2020-07-06 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudemo', '0002_auto_20200706_0629'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskdata',
            old_name='cost',
            new_name='zipcode',
        ),
        migrations.RemoveField(
            model_name='taskdata',
            name='option_hours',
        ),
        migrations.RemoveField(
            model_name='taskdata',
            name='options',
        ),
        migrations.RemoveField(
            model_name='taskdata',
            name='shoping_site_content',
        ),
        migrations.RemoveField(
            model_name='taskdata',
            name='tech_talk',
        ),
        migrations.RemoveField(
            model_name='taskdata',
            name='type',
        ),
        migrations.RemoveField(
            model_name='taskdata',
            name='weight',
        ),
        migrations.AddField(
            model_name='taskdata',
            name='address',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='taskdata',
            name='address2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='taskdata',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='taskdata',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='taskdata',
            name='state',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='taskdata',
            name='status',
            field=models.CharField(blank=True, choices=[('active', 'ACTIVE'), ('inactive', 'INACTIVE')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='taskdata',
            name='name',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
