# Generated by Django 3.0.8 on 2020-07-06 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudemo', '0003_auto_20200706_0721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskdata',
            name='status',
            field=models.CharField(blank=True, choices=[('active', 'ACTIVE'), ('inactive', 'INACTIVE')], default='inactive', max_length=50, null=True),
        ),
    ]
